---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: rchain/buildenv:latest
  commands:
  - git clone --branch=dev https://github.com/rchain/rchain.git .
  - git rev-parse HEAD

- name: compile
  image: rchain/buildenv:latest
  environment:
    _JAVA_OPTIONS: -Xms2G -Xmx4G -Xss2m -XX:MaxMetaspaceSize=1G -Dsbt.task.timings=true -Dsbt.task.timings.on.shutdown=true -Dsbt.task.timings.threshold=2000
  commands:
  - sbt update rholang/bnfc:generate test:compile

- name: slowcooker
  image: rchain/buildenv:latest
  environment:
    _JAVA_OPTIONS: -Xms2G -Xmx4G -Xss2m -XX:MaxMetaspaceSize=1G -Dsbt.task.timings=true -Dsbt.task.timings.on.shutdown=true -Dsbt.task.timings.threshold=2000
  commands:
  - sbt slowcooker:test
